apiVersion: v1
kind: Pod
metadata:
  name: db-api
  labels:
    app: db-api
spec:
  containers:
    - name: db-api-container
      image: mysql:latest
      ports:
        - containerPort: 3306
      env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "admin"
        - name: "MYSQL_DATABASE"
          value: "controle"
